import { type InsertEvent } from "../shared/schema";

export const saudiEvents: InsertEvent[] = [
  {
    title: "مهرجان الجنادرية الثقافي",
    description: "المهرجان الوطني للتراث والثقافة، يعرض التراث السعودي الأصيل ويقدم عروضًا ثقافية وفنية متنوعة من مختلف مناطق المملكة.",
    location: "الرياض",
    city: "الرياض",
    date: new Date("2023-12-20"),
    endDate: new Date("2024-01-10"),
    price: 50,
    capacity: 10000,
    remainingTickets: 5000,
    category: "ثقافي",
    imageUrl: "https://www.arabnews.com/sites/default/files/styles/n_670_395/public/2018/12/21/1399546-1993948866.jpg",
    videoUrl: "https://www.youtube.com/watch?v=JgF_pz9WRIU",
    organizer: "الهيئة العامة للترفيه",
    featured: true,
    trending: true
  },
  {
    title: "مهرجان البحر الأحمر السينمائي",
    description: "أحد أكبر المهرجانات السينمائية في المنطقة، يعرض أفلامًا عالمية وعربية متميزة ويستضيف نجوم السينما من مختلف أنحاء العالم.",
    location: "جدة البلد",
    city: "جدة",
    date: new Date("2023-12-01"),
    endDate: new Date("2023-12-10"),
    price: 150,
    capacity: 5000,
    remainingTickets: 1200,
    category: "ثقافي",
    imageUrl: "https://www.arabnews.com/sites/default/files/styles/n_670_395/public/2022/10/18/3378831-1628050938.jpg",
    videoUrl: "https://www.youtube.com/watch?v=7EHp32YKF0k",
    organizer: "مؤسسة مهرجان البحر الأحمر السينمائي",
    featured: true,
    trending: true
  },
  {
    title: "حفل محمد عبده",
    description: "حفل غنائي لفنان العرب محمد عبده، يقدم فيه باقة من أجمل أغانيه الشهيرة والجديدة.",
    location: "بوليفارد رياض سيتي",
    city: "الرياض",
    date: new Date("2023-11-15"),
    price: 300,
    capacity: 15000,
    remainingTickets: 3000,
    category: "موسيقي",
    imageUrl: "https://static.wixstatic.com/media/9e8e28_f77c131173134dde9de70b1b06cbf9ed~mv2.png/v1/fill/w_640,h_362,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/9e8e28_f77c131173134dde9de70b1b06cbf9ed~mv2.png",
    videoUrl: "https://www.youtube.com/watch?v=YdwNvI6oBMw",
    organizer: "الهيئة العامة للترفيه",
    featured: false,
    trending: true
  },
  {
    title: "معرض الرياض الدولي للكتاب",
    description: "أكبر معرض للكتاب في المملكة، يضم أجنحة لدور نشر محلية وعربية وعالمية، ويشمل جلسات نقاشية وتوقيع كتب.",
    location: "واجهة الرياض",
    city: "الرياض",
    date: new Date("2023-10-12"),
    endDate: new Date("2023-10-22"),
    price: 0,
    capacity: 50000,
    remainingTickets: 25000,
    category: "ثقافي",
    imageUrl: "https://www.spa.gov.sa/file/article/2202575/large.jpg",
    videoUrl: "https://www.youtube.com/watch?v=vLTBQJgYVZU",
    organizer: "وزارة الثقافة",
    featured: true,
    trending: false
  },
  {
    title: "موسم الرياض",
    description: "سلسلة من الفعاليات والعروض الترفيهية المتنوعة التي تقام في مختلف مناطق مدينة الرياض، تشمل حفلات وعروض مسرحية ومعارض وغيرها.",
    location: "مناطق متعددة - الرياض",
    city: "الرياض",
    date: new Date("2023-10-15"),
    endDate: new Date("2024-01-15"),
    price: 100,
    capacity: 100000,
    remainingTickets: 45000,
    category: "ترفيهي",
    imageUrl: "https://pbs.twimg.com/media/FCN6_MtXEAE55jT.jpg",
    videoUrl: "https://www.youtube.com/watch?v=EG2whz_fZWA",
    organizer: "الهيئة العامة للترفيه",
    featured: true,
    trending: true
  },
  {
    title: "معرض التصميم السعودي",
    description: "معرض مخصص لعرض إبداعات المصممين السعوديين في مجالات الأزياء والمجوهرات والديكور والفنون البصرية.",
    location: "مركز الملك عبدالله المالي",
    city: "الرياض",
    date: new Date("2023-11-05"),
    endDate: new Date("2023-11-15"),
    price: 75,
    capacity: 7000,
    remainingTickets: 2500,
    category: "ثقافي",
    imageUrl: "https://media-afr-cdn.architizer.com/thumbnails-PRODUCTION/44/5c/445cf0d14e5ba8a9481174ac86a2c6ca.jpg",
    videoUrl: "https://www.youtube.com/watch?v=ZQY_YBroPmw",
    organizer: "هيئة التصميم والفنون",
    featured: false,
    trending: true
  },
  {
    title: "مباراة الهلال والنصر (الديربي)",
    description: "مباراة كلاسيكية في الدوري السعودي للمحترفين بين فريقي الهلال والنصر.",
    location: "استاد الملك فهد الدولي",
    city: "الرياض",
    date: new Date("2023-12-30"),
    price: 150,
    capacity: 68000,
    remainingTickets: 12000,
    category: "رياضي",
    imageUrl: "https://www.arabnews.com/sites/default/files/styles/n_670_395/public/2023/04/18/3693631-2058256387.jpg?itok=45cQCGEw",
    videoUrl: "https://www.youtube.com/watch?v=S4_oeQCZ8b4",
    organizer: "وزارة الرياضة",
    featured: true,
    trending: true
  },
  {
    title: "مؤتمر مستقبل الاستثمار",
    description: "مؤتمر عالمي يجمع قادة الأعمال والمستثمرين لمناقشة فرص الاستثمار المستقبلية في المملكة والعالم.",
    location: "مركز الملك عبدالعزيز الدولي للمؤتمرات",
    city: "الرياض",
    date: new Date("2024-01-25"),
    endDate: new Date("2024-01-27"),
    price: 5000,
    capacity: 3000,
    remainingTickets: 1000,
    category: "أعمال",
    imageUrl: "https://pbs.twimg.com/media/FfKLPtHXkAA4S8b.jpg",
    videoUrl: "https://www.youtube.com/watch?v=TS-Boby1_kc",
    organizer: "صندوق الاستثمارات العامة",
    featured: true,
    trending: false
  },
  {
    title: "مهرجان الإبل (مهرجان الملك عبدالعزيز للإبل)",
    description: "مهرجان سنوي يحتفي بتراث الإبل في الثقافة السعودية، ويضم مسابقات جمال الإبل وسباقات ومزادات وفعاليات ثقافية مصاحبة.",
    location: "الصياهد - الدهناء",
    city: "الرياض",
    date: new Date("2023-11-01"),
    endDate: new Date("2023-12-15"),
    price: 50,
    capacity: 30000,
    remainingTickets: 17000,
    category: "ثقافي",
    imageUrl: "https://scontent.cdninstagram.com/v/t51.2885-15/322587070_693256515784465_2283375951300799997_n.jpg?stp=dst-jpg_e35_s1080x1080&_nc_ht=scontent.cdninstagram.com&_nc_cat=108&_nc_ohc=LJ7gp6ZQB6AAX_WxAmP&edm=APs17CUBAAAA&ccb=7-5&ig_cache_key=MzAwMzI2MzgxOTM2NzA1OTM1NQ%3D%3D.2-ccb7-5&oh=00_AfCs76h5bxMuHQ3VUqBx7PFMH2vkVcv22QBdP3KX6pRm6w&oe=64A40A21&_nc_sid=10d13b",
    videoUrl: "https://www.youtube.com/watch?v=sR-Qh3oIZXY",
    organizer: "نادي الإبل السعودي",
    featured: false,
    trending: true
  },
  {
    title: "مهرجان البحر الأحمر للأفلام",
    description: "مهرجان سينمائي يعرض أحدث الأفلام العربية والعالمية في دورته الثالثة، مع ندوات ومناقشات مع صناع الأفلام.",
    location: "القاعدة البحرية - البلد",
    city: "جدة",
    date: new Date("2023-11-30"),
    endDate: new Date("2023-12-09"),
    price: 75,
    capacity: 9000,
    remainingTickets: 3700,
    category: "ثقافي",
    imageUrl: "https://www.arabnews.com/sites/default/files/styles/n_670_395/public/main-image/2022/12/11/3494091-1427159832.jpg?itok=PkXkHY-I",
    videoUrl: "https://www.youtube.com/watch?v=SdtkJbKdTAU",
    organizer: "مؤسسة مهرجان البحر الأحمر",
    featured: true,
    trending: true
  },
  {
    title: "المعرض السعودي الدولي للسيارات",
    description: "معرض يضم أحدث موديلات السيارات العالمية والمحلية، مع عروض وفعاليات مصاحبة للهواة والمختصين.",
    location: "مركز الرياض الدولي للمعارض والمؤتمرات",
    city: "الرياض",
    date: new Date("2024-01-05"),
    endDate: new Date("2024-01-12"),
    price: 45,
    capacity: 20000,
    remainingTickets: 11000,
    category: "ترفيهي",
    imageUrl: "https://www.arabnews.com/sites/default/files/styles/n_670_395/public/2022/11/30/3484581-1363095281.jpg?itok=ZG2kyKvB",
    videoUrl: "https://www.youtube.com/watch?v=P-nFejGUDFw",
    organizer: "هيئة تطوير المعارض والمؤتمرات",
    featured: false,
    trending: true
  },
  {
    title: "أنمي إكسبو السعودية",
    description: "أكبر تجمع لمحبي الأنمي والمانجا في المملكة، يضم معارض ومسابقات وفعاليات وعروض على الطراز الياباني.",
    location: "واجهة الرياض",
    city: "الرياض",
    date: new Date("2023-11-23"),
    endDate: new Date("2023-11-25"),
    price: 85,
    capacity: 12000,
    remainingTickets: 4300,
    category: "ترفيهي",
    imageUrl: "https://cdn.sabq.org/uploads/media-cache/resize_800/uploads/material-file/627bf8033dc9cf83c78be0f2/627bf7fc8da97.jpg",
    videoUrl: "https://www.youtube.com/watch?v=ZbmRZGBJ0_4",
    organizer: "الهيئة العامة للترفيه",
    featured: true,
    trending: true
  },
  {
    title: "ويك آب السعودية",
    description: "فعالية لصناعة الألعاب الإلكترونية والرياضات الإلكترونية، تضم بطولات وورش عمل ومعارض.",
    location: "بوليفارد رياض سيتي",
    city: "الرياض",
    date: new Date("2023-12-08"),
    endDate: new Date("2023-12-10"),
    price: 95,
    capacity: 8000,
    remainingTickets: 2400,
    category: "ترفيهي",
    imageUrl: "https://m.eyeofriyadh.com/directory/images/2022/07/a8ed9f336af2.jpg",
    videoUrl: "https://www.youtube.com/watch?v=1fgOjPHdTvE",
    organizer: "اتحاد الرياضات الإلكترونية",
    featured: false,
    trending: true
  },
  {
    title: "مهرجان ميدل بيست",
    description: "مهرجان موسيقي عالمي يجمع نخبة من النجوم العالميين والعرب في حفلات موسيقية متنوعة.",
    location: "جزيرة الأحلام - الخبر",
    city: "الخبر",
    date: new Date("2023-12-20"),
    endDate: new Date("2023-12-22"),
    price: 350,
    capacity: 25000,
    remainingTickets: 8000,
    category: "موسيقي",
    imageUrl: "https://www.arabnews.com/sites/default/files/styles/n_670_395/public/2022/12/02/3487531-1818400851.jpg?itok=9dFKTaaN",
    videoUrl: "https://www.youtube.com/watch?v=f4DomXVTL3U",
    organizer: "MDL BEAST",
    featured: true,
    trending: true
  },
  {
    title: "فورمولا 1 جدة",
    description: "سباق الجائزة الكبرى للفورمولا 1 في جدة، على أسرع حلبة شوارع في العالم.",
    location: "حلبة كورنيش جدة",
    city: "جدة",
    date: new Date("2024-03-08"),
    endDate: new Date("2024-03-10"),
    price: 400,
    capacity: 40000,
    remainingTickets: 15000,
    category: "رياضي",
    imageUrl: "https://www.motorsport.com/jp/f1/news/saudi-arabia-f1-race-most-exciting-venue-2020/4906502/track-layout.jpg",
    videoUrl: "https://www.youtube.com/watch?v=UlVydVjJTKM",
    organizer: "وزارة الرياضة",
    featured: true,
    trending: true
  }
];

// فيديوهات للعروض المميزة
export const trendingVideos = [
  {
    title: "مهرجان الجنادرية",
    videoUrl: "https://www.youtube.com/watch?v=JgF_pz9WRIU",
    thumbnailUrl: "https://www.arabnews.com/sites/default/files/styles/n_670_395/public/2018/12/21/1399546-1993948866.jpg"
  },
  {
    title: "موسم الرياض",
    videoUrl: "https://www.youtube.com/watch?v=EG2whz_fZWA",
    thumbnailUrl: "https://pbs.twimg.com/media/FCN6_MtXEAE55jT.jpg"
  },
  {
    title: "مهرجان البحر الأحمر السينمائي",
    videoUrl: "https://www.youtube.com/watch?v=7EHp32YKF0k",
    thumbnailUrl: "https://www.arabnews.com/sites/default/files/styles/n_670_395/public/2022/10/18/3378831-1628050938.jpg"
  },
  {
    title: "فورمولا 1 جدة",
    videoUrl: "https://www.youtube.com/watch?v=UlVydVjJTKM",
    thumbnailUrl: "https://www.motorsport.com/jp/f1/news/saudi-arabia-f1-race-most-exciting-venue-2020/4906502/track-layout.jpg"
  },
  {
    title: "مهرجان ميدل بيست",
    videoUrl: "https://www.youtube.com/watch?v=f4DomXVTL3U",
    thumbnailUrl: "https://www.arabnews.com/sites/default/files/styles/n_670_395/public/2022/12/02/3487531-1818400851.jpg?itok=9dFKTaaN"
  }
];